### ISSUE TITLE
How to jump up a state to make a infinity loop

### ISSUE THREAD

**Issue by shaolinkhoa** [dgtony/afg#3]
Hi,

I want to jump up the state without using a addition ask_continue_intent. 
So that I can make a infinity loop to give command to Alexa continuously.

This is what I tried:

**scenario.yaml**
```
steps:
  # the first step
  init:
    events:
      launched: 
        next: center 

  center:
    reprompt:
      - "Sorry, I didn't understand"
      - "Please ask help for more information"
    help:
      - "For example, just say: who are you"
      - "For example, just say: turn on the light"
    events:
      PlayMusicIntent_trigger: 
        next: waitting 
      ControlDeviceIntent_trigger: 
        next: waitting 

  waitting:
    reprompt:
      - "Sorry, I didn't understand"
      - "Please ask help for more information"
    help:
      - "For example, just say: who are you"
      - "For example, just say: turn on the light"
    events:
      PlayMusicIntent_trigger:
        next: done 
      ControlDeviceIntent_trigger: 
        next: done 
     
  done:
```

**server flask-ask**
```

Sup_Current_state = "none" 

@ask.intent("PlayMusicIntent")
@sup.guide
def PlayMusicIntent_trigger(Song):

    global Sup_Current_state
    Sup_Current_state = sup.get_current_state()

    global PlayMusic_trigger,PlayMusic_song,PlayMusic_status
    PlayMusic_trigger = True
    PlayMusic_song = Song
    PlayMusic_status = "playing"

    if Sup_Current_state is "done":
        sup.move_to_step('center')
        return question(render_template('PlayMusic_done',song=PlayMusic_song))

    return question(render_template('PlayMusic_done',song=PlayMusic_song))

@ask.intent('ControlDeviceIntent')
@sup.guide
def ControlDeviceIntent_trigger(Status,Device): 

    global Sup_Current_state
    Sup_Current_state = sup.get_current_state()
 
    global ControlDevice_trigger,ControlDevice_device,ControlDevice_status

    #save the status of the device to send to gateway
    ControlDevice_trigger = True
    ControlDevice_device = Device
    ControlDevice_status = Status

    if Sup_Current_state is "done":
        sup.move_to_step('center') 
        return question(render_template('ControlDevice_done',device=Device, status=Status))   

    return question(render_template('ControlDevice_done',device=Device, status=Status))
```

I can send the first command in **center** state and second command in **waitting** state.
But after it finished **waitting** state. If I give the third command, Alexa will return an error.

I don't understand. If I create a addition state _ask_keep_continue_or_not_, It works perfectly but I have to say _yes_ to keep the loop.

would you mind helping me ?
