### ISSUE TITLE
KeyError: 'reprompt'

### ISSUE THREAD

**Issue by Rick-OS** [dgtony/afg#5]
when running the example the following keyerror is thrown

File "/usr/local/lib/python2.7/dist-packages/afg/scenarios.py", line 110, in guide
    return question(choice(self._scenario_steps[current_state]['reprompt']))

**Comment by Rick-OS** [comment]
yes - it appears the current state variable in the scenarios.py is set to init rather than moving on to drink_choice which is why i get the key error. If i manually set it to drink_choice it moves on.

**Comment by Rick-OS** [comment]
I can also define a 'reprompt:' field within the initial scenario.yaml so the key does exist, but im still not getting to the next step.

**Comment by dgtony** [comment]
Well, problem may be in the scenario usage.
Original scenario was intended to be invoked with no specific intent. In this case Alexa sends `LaunchRequest` to the service and state machine immediately moves from `init` to `drink_choice` and thus required no reprompt. 
But if you invoke the skill with some intent, Alexa sends `IntentRequest` and scenario has no appropriate paths for it. If this is the case, you can fix the `init` step:

```
  init:
    reprompt:
      - "Hi, what drink do you prefer?"
    events:
      launched:
        next: drink_choice
      choose_tea:
        next: drink_amount_choice
      choose_coffee:
        next: coffee_strength_choice
```
